"""Pretty terminal reporting and a markdown model card for a training run."""

from __future__ import annotations

from .audit import AuditResult
from .core import TrainResult

_RULE = "─" * 56


def format_report(r: TrainResult) -> str:
    lines = [_RULE,
             f"  tabml · {r.task.upper()}  —  target: {r.target}",
             _RULE,
             f"  rows: {r.n_rows:,}   features: {r.n_features}   "
             f"trained in {r.elapsed_s}s",
             ""]

    lines.append(f"  Model comparison ({r.cv_metric}, {len(r.cv_scores)} models, CV):")
    best = max(r.cv_scores.values()) if r.cv_scores else None
    for name, score in sorted(r.cv_scores.items(), key=lambda kv: kv[1], reverse=True):
        marker = "►" if score == best else " "
        bar = "█" * int(max(0.0, min(1.0, score)) * 24)
        lines.append(f"   {marker} {name:<20} {score:>7.4f}  {bar}")
    lines.append("")

    lines.append(f"  Best model: {r.best_model}")
    lines.append("  Held-out test metrics:")
    for k, v in r.test_metrics.items():
        lines.append(f"    {k:<14} {v}")
    if r.class_labels is not None:
        labels = ", ".join(str(c) for c in r.class_labels[:8])
        more = " …" if len(r.class_labels) > 8 else ""
        lines.append(f"    classes        {labels}{more}")

    if r.importances:
        lines.append("")
        lines.append("  Top features:")
        top = r.importances[:8]
        mx = max(v for _, v in top) or 1.0
        for name, val in top:
            bar = "▮" * int((val / mx) * 18)
            lines.append(f"    {name[:28]:<28} {val:>6.3f}  {bar}")
    lines.append(_RULE)
    return "\n".join(lines)


def format_audit(a: AuditResult) -> str:
    lines = [_RULE,
             f"  tabml audit · {a.task.upper()}  —  target: {a.target}",
             _RULE,
             f"  rows: {a.n_rows:,}   features: {a.n_features}",
             ""]
    if not a.findings:
        lines.append("  ✓ no issues found — data looks clean.")
        lines.append(_RULE)
        return "\n".join(lines)

    icon = {"leak": "⛔ LEAK", "warn": "⚠ WARN", "info": "· info"}
    if a.leaks:
        lines.append("  ⛔ TARGET LEAKAGE SUSPECTS — investigate before trusting any score:")
        for f in a.leaks:
            lines.append(f"     {f.column}: {f.message}")
        lines.append("")
    for f in a.findings:
        if f.severity == "leak":
            continue
        lines.append(f"  {icon[f.severity]:<7} {f.column}: {f.message}")
    lines.append(_RULE)
    return "\n".join(lines)


def model_card(r: TrainResult) -> str:
    """A shareable markdown model card documenting the trained model."""
    md = [f"# Model Card — `{r.target}` {r.task}", ""]
    md.append(f"- **Task:** {r.task}")
    md.append(f"- **Best model:** {r.best_model}")
    md.append(f"- **Training rows:** {r.n_rows:,}")
    md.append(f"- **Features:** {r.n_features}")
    if r.class_labels is not None:
        md.append(f"- **Classes:** {', '.join(str(c) for c in r.class_labels)}")
    md.append("")
    md.append("## Held-out test metrics")
    md.append("")
    md.append("| Metric | Value |")
    md.append("|---|---|")
    for k, v in r.test_metrics.items():
        md.append(f"| {k} | {v} |")
    md.append("")
    md.append(f"## Model comparison (CV, {r.cv_metric})")
    md.append("")
    md.append("| Model | Score |")
    md.append("|---|---|")
    for name, score in sorted(r.cv_scores.items(), key=lambda kv: kv[1], reverse=True):
        md.append(f"| {name} | {score} |")
    if r.importances:
        md.append("")
        md.append("## Top features")
        md.append("")
        md.append("| Feature | Importance |")
        md.append("|---|---|")
        for name, val in r.importances[:12]:
            md.append(f"| {name} | {val} |")
    md.append("")
    md.append("_Generated by [tabml](https://github.com/SriniV-1/tabml)._")
    return "\n".join(md)
